version: "3.9"
services:
  app:
    container_name: helper-v3
    ports:
      - 8888:8888
    build:
      context: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PEPAL_BASE_URL=${PEPAL_BASE_URL}